openapi: 3.2.0
info:
  title: Agent Attachments API
  description: 'This document refers to Symphony API calls to send and receive messages

    and content.'
  version: 25.8.1
servers:
- url: youragentURL.symphony.com/agent
tags:
- name: Attachments
paths:
  /v1/stream/{sid}/attachment:
    get:
      tags:
      - Attachments
      summary: Download an attachment
      description: Downloads the attachment body by the attachment ID, stream ID, and message ID.
      parameters:
      - name: sid
        in: path
        description: Stream ID
        required: true
        schema:
          type: string
      - name: fileId
        in: query
        description: The attachment ID (Base64-encoded)
        required: true
        schema:
          type: string
      - name: messageId
        in: query
        description: The ID of the message containing the attachment
        required: true
        schema:
          type: string
      - name: sessionToken
        in: header
        description: Session authentication token.
        required: true
        schema:
          type: string
      - name: keyManagerToken
        in: header
        description: Key Manager authentication token.
        schema:
          type: string
      responses:
        200:
          description: Attachment body as Base64 encoded string.
          content:
            application/octet-stream:
              schema:
                type: string
                format: byte
        400:
          description: Client error, see response body for further details.
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 'Unauthorized: Session tokens invalid.'
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server error, see response body for further details.
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: getV1StreamBySidAttachment
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
