openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod Disclaimer API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.


    - sessionToken can be obtained by calling the

    authenticationAPI on the symphony back end and the key manager

    respectively. Refer to the methods described in authenticatorAPI.yaml.

    - Actions are defined to be atomic, ie will succeed in their entirety

    or fail and have changed nothing.

    - If it returns a 40X status then it will have made no change to the

    system even if ome subset of the request would have succeeded.

    - If this contract cannot be met for any reason then this is an error

    and the response code will be 50X.

    '
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: Disclaimer
paths:
  /v1/admin/disclaimer/{did}:
    get:
      summary: Get a disclaimer by disclaimer id
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: did
        in: path
        description: The ID of the entity
        required: true
        schema:
          type: string
      tags:
      - Disclaimer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disclaimer'
              example:
                id: 571d20dae4b042aaf06d2e7c
                name: New Enterprise Disclaimer
                content: This is a second enterprise disclaimer.
                frequencyInHours: 168
                isDefault: false
                isActive: true
                createdDate: 1461526746875
                modifiedDate: 1461526746875
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
  /v1/admin/disclaimer/list:
    get:
      summary: List all disclaimers for the company (pod)
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - Disclaimer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisclaimerList'
              example:
              - id: 571d2052e4b042aaf06d2e7a
                name: Enterprise Disclaimer
                content: This is a disclaimer for the enterprise.
                frequencyInHours: 24
                isDefault: false
                isActive: true
                createdDate: 1461526610846
                modifiedDate: 1461526610846
              - id: 571d20dae4b042aaf06d2e7c
                name: New Enterprise Disclaimer
                content: This is a second enterprise disclaimer.
                frequencyInHours: 168
                isDefault: false
                isActive: true
                createdDate: 1461526746875
                modifiedDate: 1461526746875
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
  /v1/admin/disclaimer/{did}/users:
    get:
      summary: List all users assigned to this disclaimer
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: did
        in: path
        description: The ID of the entity
        required: true
        schema:
          type: string
      tags:
      - Disclaimer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserIdList'
              example:
              - 7215545078541
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
    UserIdList:
      type: array
      items:
        type: integer
        format: int64
      example:
      - 7215545058313
      - 7215545078461
    DisclaimerList:
      type: array
      items:
        $ref: '#/components/schemas/Disclaimer'
      example:
      - id: 571d2052e4b042aaf06d2e7a
        name: Enterprise Disclaimer
        content: This is a disclaimer for the enterprise.
        frequencyInHours: 24
        isDefault: false
        isActive: true
        createdDate: 1461526610846
        modifiedDate: 1461526610846
      - id: 571d20dae4b042aaf06d2e7c
        name: New Enterprise Disclaimer
        content: This is a second enterprise disclaimer.
        frequencyInHours: 168
        isDefault: false
        isActive: true
        createdDate: 1461526746875
        modifiedDate: 1461526746875
    Disclaimer:
      type: object
      properties:
        id:
          type: string
          example: 571d20dae4b042aaf06d2e7c
        name:
          type: string
          example: New Enterprise Disclaimer
        content:
          type: string
          example: This is a second enterprise disclaimer.
        frequencyInHours:
          type: integer
          format: int32
          example: 168
        isDefault:
          type: boolean
          example: false
        isActive:
          type: boolean
          example: true
        createdDate:
          type: integer
          format: int64
          example: 1461526746875
        modifiedDate:
          type: integer
          format: int64
          example: 1461526746875
        format:
          type: string
          enum:
          - TEXT
          - XML
          example: TEXT
