openapi: 3.2.0
info:
  version: 20.17.1
  title: Pod Info Barriers API
  description: 'This document refers to Symphony API calls that do not need

    encryption or decryption of content.'
servers:
- url: https://yourpodURL.symphony.com/pod
tags:
- name: InfoBarriers
paths:
  /v1/admin/group/list:
    get:
      summary: Get a list of all Information Barrier Groups
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - InfoBarriers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupList'
              example:
              - id: 571db1f2e4b027c4f055a594
                name: Group 1
                active: true
                memberCount: 1
                policies:
                - 571db2e4e4b012df6341f393
                createdDate: 1461563890135
                modifiedDate: 1461563926812
              - id: 571db20ae4b012df6341f391
                name: Group 2
                active: true
                memberCount: 1
                policies:
                - 571db2e4e4b012df6341f393
                createdDate: 1461563914581
                modifiedDate: 1461564112286
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1AdminGroupList
      x-operation-id-source: derived
  /v1/admin/group/{gid}/membership/list:
    get:
      summary: Get the list of userids in this Information Barrier Group
      parameters:
      - name: gid
        description: URL-Safe encoded Group ID
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      - name: skip
        description: Number of records to skip. Must be a positive integer.
        in: query
        required: false
        x-since: 20.15
        schema:
          type: integer
      - name: limit
        description: Max number of records to return. Default is 10000. Must be a positive integer and must not exceed 10000.
        in: query
        required: false
        x-since: 20.15
        schema:
          type: integer
      tags:
      - InfoBarriers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegerList'
              example:
              - 7215545078541
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '404':
          description: 'Not Found: Group cannot be found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: // Not Found. Group cannot be found. See response body for fruther details.
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1AdminGroupByGidMembershipList
      x-operation-id-source: derived
  /v1/admin/group/{gid}/membership/add:
    post:
      summary: Add members to an Information Barrier group
      parameters:
      - name: gid
        description: URL-Safe encoded Group ID
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - InfoBarriers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkActionResult'
              example:
                overallResult: SUCCESS
                results:
                - ''
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntegerList'
        required: true
      operationId: postV1AdminGroupByGidMembershipAdd
      x-operation-id-source: derived
  /v1/admin/group/{gid}/membership/remove:
    post:
      summary: Remove members from an Information Barrier group
      parameters:
      - name: gid
        description: URL-Safe encoded Group ID
        in: path
        required: true
        schema:
          type: string
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - InfoBarriers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkActionResult'
              example:
                overallResult: SUCCESS
                results:
                - ''
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntegerList'
        required: true
      operationId: postV1AdminGroupByGidMembershipRemove
      x-operation-id-source: derived
  /v1/admin/policy/list:
    get:
      summary: Get all Information Policies
      parameters:
      - name: sessionToken
        description: Session authentication token.
        in: header
        required: true
        schema:
          type: string
      tags:
      - InfoBarriers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyList'
              example:
              - id: 56e9df05e4b00737e3d3b82d
                policyType: BLOCK
                active: true
                groups:
                - 56e9def8e4b0b406041812e6
                - 56e9deffe4b0b406041812e7
                createdDate: 1458167557358
                modifiedDate: 1458330606752
              - id: 571cd64de4b042aaf06d2d8b
                policyType: BLOCK
                active: true
                groups:
                - 571cd646e4b042aaf06d2d84
                - 571cd64ce4b042aaf06d2d8a
                createdDate: 1461507661146
                modifiedDate: 1461507661146
        '400':
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 400
                message: // Client error, see response body for further details.
        '401':
          description: 'Unauthorized: Invalid session token.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 401
                message: Invalid session
        '403':
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 403
                message: The user lacks the required entitlement to perform this operation
        '500':
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: // Server error, see response body for further details.
      operationId: getV1AdminPolicyList
      x-operation-id-source: derived
components:
  schemas:
    Policy:
      description: Information Barrier Policy record.
      type: object
      properties:
        id:
          type: string
          example: 56e9df05e4b00737e3d3b82d
        policyType:
          type: string
          enum:
          - BLOCK
          - ALLOW
          example: BLOCK
        active:
          type: boolean
          example: true
        memberCount:
          type: integer
          format: int32
          example: 3
        groups:
          type: array
          items:
            type: string
          example:
          - 56e9deffe4b0b406041812e6
          - 56e9deffe4b0b406041812e7
        createdDate:
          type: integer
          format: int64
          example: 1458167557358
        modifiedDate:
          type: integer
          format: int64
          example: 1458330606752
    GroupList:
      type: array
      items:
        $ref: '#/components/schemas/Group'
      example:
      - id: 571db1f2e4b027c4f055a594
        name: Group 1
        active: true
        memberCount: 1
        policies:
        - 571db2e4e4b012df6341f393
        createdDate: 1461563890135
        modifiedDate: 1461563926812
      - id: 571db20ae4b012df6341f391
        name: Group 2
        active: true
        memberCount: 1
        policies:
        - 571db2e4e4b012df6341f393
        createdDate: 1461563914581
        modifiedDate: 1461564112286
    Group:
      description: Information Barrier Group record.
      type: object
      properties:
        id:
          type: string
          example: 571db1f2e4b027c4f055a594
        name:
          type: string
          example: Group 1
        active:
          type: boolean
          example: true
        memberCount:
          type: integer
          format: int32
          example: 1
        policies:
          type: array
          items:
            type: string
          example:
          - 571db2e4e4b012df6341f393
        createdDate:
          type: integer
          format: int64
          example: 1461563890135
        modifiedDate:
          type: integer
          format: int64
          example: 1461563926812
    PolicyList:
      type: array
      items:
        $ref: '#/components/schemas/Policy'
      example:
      - id: 56e9df05e4b00737e3d3b82d
        policyType: BLOCK
        active: true
        groups:
        - 56e9def8e4b0b406041812e6
        - 56e9deffe4b0b406041812e7
        createdDate: 1458167557358
        modifiedDate: 1458330606752
      - id: 571cd64de4b042aaf06d2d8b
        policyType: BLOCK
        active: true
        groups:
        - 571cd646e4b042aaf06d2d84
        - 571cd64ce4b042aaf06d2d8a
        createdDate: 1461507661146
        modifiedDate: 1461507661146
    BulkActionResult:
      description: 'The results of list based bulk action. The list contains the result messages

        in the same order as submitted. The message will be an empty string if the action

        was successful for item in that index.

        '
      properties:
        overallResult:
          type: string
          enum:
          - SUCCESS
          - FAIL
          example: SUCCESS
        results:
          type: array
          items:
            type: string
          example:
          - ''
    IntegerList:
      type: array
      items:
        type: integer
        format: int64
      example:
      - 1461508270000
      - 7215545057281
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 401
        message:
          type: string
          example: Invalid session
