openapi: 3.2.0
info:
  title: Agent Share API
  description: 'This document refers to Symphony API calls to send and receive messages

    and content.'
  version: 25.8.1
servers:
- url: youragentURL.symphony.com/agent
tags:
- name: Share
paths:
  /v3/stream/{sid}/share:
    post:
      tags:
      - Share
      summary: PROVISIONAL - Share a piece of content into Symphony
      description: 'Given a 3rd party content (eg. news article), it can share to the given stream.

        The stream can be a chatroom, an IM or a multiparty IM.'
      parameters:
      - name: sid
        in: path
        description: Stream ID
        required: true
        schema:
          type: string
      - name: sessionToken
        in: header
        description: Session authentication token.
        required: true
        schema:
          type: string
      - name: keyManagerToken
        in: header
        description: Key Manager authentication token.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareContent'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V2Message'
        400:
          description: Client error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 'Unauthorized: Session tokens invalid.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: 'Forbidden: Caller lacks necessary entitlement.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Server error, see response body for further details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: shareContent
      operationId: postV3StreamBySidShare
      x-operation-id-source: derived
components:
  schemas:
    ShareContent:
      type: object
      properties:
        type:
          type: string
          description: Type of content to be shared.  Currently only support "com.symphony.sharing.article"
        content:
          $ref: '#/components/schemas/ShareArticle'
    ShareArticle:
      required:
      - appId
      - author
      - publisher
      - title
      type: object
      properties:
        articleId:
          type: string
          description: "An ID for this article that should be unique to the calling application. \nEither an articleId or an articleUrl is required.\n"
        title:
          type: string
          description: The title of the article
        subTitle:
          type: string
          description: The subtitle of the article
        message:
          type: string
          description: The message text that can be send along with the shared article
        publisher:
          type: string
          description: Publisher of the article
        publishDate:
          type: integer
          description: Article publish date in unix timestamp
          format: int64
        thumbnailUrl:
          type: string
          description: Url to the thumbnail image
        author:
          type: string
          description: Author of the article
        articleUrl:
          type: string
          description: Url to the article
        summary:
          type: string
          description: Preview summary of the article
        appId:
          type: string
          description: App ID of the calling application
        appName:
          type: string
          description: App name of the calling application
        appIconUrl:
          type: string
          description: App icon url of the calling application
    AttachmentInfo:
      required:
      - id
      - name
      - size
      type: object
      properties:
        id:
          type: string
          description: The attachment ID.
        name:
          type: string
          description: The file name.
        size:
          type: integer
          description: Size in bytes.
          format: int64
    V2BaseMessage:
      required:
      - streamId
      - timestamp
      - v2messageType
      type: object
      properties:
        id:
          type: string
          description: The messageId is assigned by the ingestor service when a message is sent.
        timestamp:
          type: string
        v2messageType:
          type: string
        streamId:
          type: string
      discriminator:
        propertyName: v2messageType
    V2Message:
      description: A representation of a message sent by a user of Symphony.
      allOf:
      - $ref: '#/components/schemas/V2BaseMessage'
      - required:
        - fromUserId
        - message
        type: object
        properties:
          message:
            type: string
            description: Message text in MessageML
            format: MessageML
          fromUserId:
            type: integer
            description: the Symphony userId of the user who sent the message. This will be populated by the server (and actually ignored if included when sending a message).
            format: int64
          attachments:
            type: array
            default: []
            items:
              $ref: '#/components/schemas/AttachmentInfo'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
